spring:
  datasource:
    url: jdbc:h2:mem:javaflow_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

# Telegram Bot (Development)
javaflow:
  bot:
    telegram:
      enabled: false  # Disabled for development
    whatsapp:
      enabled: false

logging:
  level:
    com.javaflow: DEBUG
    org.flowable: INFO
    org.springframework.web: DEBUG
